module.exports = {
  TICK: 'TICK',
  APPLY_OFFLINE_PROGRESS: 'APPLY_OFFLINE_PROGRESS',
  DISMISS_OFFSEASON_SUMMARY: 'DISMISS_OFFSEASON_SUMMARY',
  ACKNOWLEDGE_VICTORY: 'ACKNOWLEDGE_VICTORY',

  SEARCH_LOT: 'SEARCH_LOT',
  BUY_LOT_ITEM: 'BUY_LOT_ITEM',
  DISMISS_STORY_BEAT: 'DISMISS_STORY_BEAT',

  RESOLVE_WALL_BALL_CHALLENGE: 'RESOLVE_WALL_BALL_CHALLENGE',
  BUY_WALL_BALL_UPGRADE: 'BUY_WALL_BALL_UPGRADE',

  BUY_CONCESSION: 'BUY_CONCESSION',

  BUY_SPONSORSHIP: 'BUY_SPONSORSHIP',
  PLACE_BOOKIE_WAGER: 'PLACE_BOOKIE_WAGER',

  SET_TICKET_PRICE: 'SET_TICKET_PRICE',
  BUY_POWERUP: 'BUY_POWERUP',
  UPGRADE_STADIUM: 'UPGRADE_STADIUM',

  BUY_STAT_UPGRADE: 'BUY_STAT_UPGRADE',
  START_CAMP: 'START_CAMP',
  EXECUTE_TRADE: 'EXECUTE_TRADE',

  PRESTIGE_RESET: 'PRESTIGE_RESET',
  BUY_PERK: 'BUY_PERK',

  MARK_TAB_SEEN: 'MARK_TAB_SEEN',

  LOAD_SAVE: 'LOAD_SAVE',
  HARD_RESET: 'HARD_RESET',
};
